### ISSUE TITLE
파일명 오타난 것 같아요

### ISSUE THREAD

**Issue by ghost** [mjkang0987/mjkang0987.github.io#3]
[여기서](https://github.com/mjkang0987/mjkang0987.github.io/tree/c079a176ead3f5df4ccb0609328be56f6acd6402/scripts) `constans.js` 파일명이 오타난 것 같습니다. `constants.js`로 바꾸는건 어떤가요?

**Comment by mjkang0987** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 아니 이런 실수를...........
