### ISSUE TITLE
리팩토링 건의 - 모듈 환경

### ISSUE THREAD

**Issue by ghost** [mjkang0987/mjkang0987.github.io#4]
모듈 내부에서는 모든 코드가 [자동으로 use strict로 작동](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules)한다고 합니다.
그래서 [여기](https://github.com/mjkang0987/mjkang0987.github.io/blob/c079a176ead3f5df4ccb0609328be56f6acd6402/scripts/weatherPrototype.js#L14)에 넣어놓은 `'use strict'`는 빼도 되지 않을까 싶습니다.

즉시 실행 함수를 사용한다면 변수들을 클로저로 묶어 밖에서 접근하지 못하게 하려고 사용하는걸로 알고있습니다.
모듈로 스크립트를 불러온다면 자동으로 [모듈 스코프가 적용되어 해당 모듈 밖에선 변수들에 접근이 불가능](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#Other_differences_between_modules_and_standard_scripts) 해집니다.
즉시실행 함수를 이용한 다른 이유가 없다면 제거하는건 어떤가요?

**Comment by mjkang0987** [comment]
아.. 요건 처음알았어요!
모듈을 사용하는 이유가 `import`의 사용을 위함이 주인줄 알았는데,
이미 모듈 타입을 사용하게되면 밖에서 접근이 불가능하군요.. 몰랐던 사실에 무릎을 탁,,,,
즉시실행함수 사용의 이유가 내부에서만 접근 가능하도록 하기위함이이었습니다.
그것이 모듈 타입을 사용함으로 인해서 해결이 되었군요 -_-;;
감삼다!! 요거 개선하겠슴다🙇‍♀️
