### ISSUE TITLE
코드 리팩토링 - 객체의 속성 대신 지역변수 사용 제안

### ISSUE THREAD

**Issue by ghost** [mjkang0987/mjkang0987.github.io#7]
https://github.com/mjkang0987/mjkang0987.github.io/blob/5ac7091aeeb401070fa3f9918fb2a16ff5ea6881/scripts/weatherPrototype.js#L90-L96

위 코드에서 `this.time`이 해당 함수 내에서만 사용됩니다. 
지역변수로 선언해 사용한다면 중복상황에 대처할 수 있고 해당 스코프 내에서만 사용된다는걸 암시적으로 알수있습니다.
그리고 구조분해할당을 이용해 좀더 간결하게 만들 수 있을 것 같아요!
```javascript
const { hour: h, minutes: m, seconds: s, } = this.getTime();

this.time = {
  hour: h < 10 ? `0${h}` : h,
  minutes: m < 10 ? `0${m}` : m,
  seconds: s
};
```
`this.hour`가 따로 할당되는 시점이 없던데 혹시 `this.gemTime.hour`인가요?

https://github.com/mjkang0987/mjkang0987.github.io/blob/5ac7091aeeb401070fa3f9918fb2a16ff5ea6881/scripts/weatherPrototype.js#L232

https://github.com/mjkang0987/mjkang0987.github.io/blob/5ac7091aeeb401070fa3f9918fb2a16ff5ea6881/scripts/weatherPrototype.js#L240

https://github.com/mjkang0987/mjkang0987.github.io/blob/5ac7091aeeb401070fa3f9918fb2a16ff5ea6881/scripts/weatherPrototype.js#L389
`firstKeyCites` 에 오타있어요! `firstKeyCities`가 맞는 것 같습니당

https://github.com/mjkang0987/mjkang0987.github.io/blob/5ac7091aeeb401070fa3f9918fb2a16ff5ea6881/scripts/weatherPrototype.js#L406

위 코드조각들도 같은 맥락이에요

----
여담으로 요번 코드리뷰가 처음인데 혹시 예시나 참고할만한 곳 있으신가요..? 이렇게 하는게 맞는건지 모르겠어요

**Comment by mjkang0987** [comment]
오옷 네넵 우선은 해당 메소드 내에서만 사용되는 변수의 경우 지역변수로 뺴보도록 하것슴당
그리고 저와 오타는 뗼래야 뗼 수 없는 사이인가보네요,,, ^^,,,, 거참,,,,,
요거 주말에 수정하는 방향으로 할게요!! 상세한 설명 감삼다!!

음 사실 저도 코드리뷰...를 해본 경험이 없긴해여 -_-;
시간 할애하셔서 이렇게 코드 봐주시는 것 만으로도 너무 감사한걸류...
게다가 디테일한 설명까지 덤으로 해주셨으니 더할나위없는 코드리뷰인것같은데여?
