### ISSUE TITLE
코드 리팩토링 - Prototype의 필요성

### ISSUE THREAD

**Issue by ghost** [mjkang0987/mjkang0987.github.io#8]
https://github.com/mjkang0987/mjkang0987.github.io/blob/5ac7091aeeb401070fa3f9918fb2a16ff5ea6881/scripts/weatherPrototype.js#L21-L46

`Prototype`으로 묶여있는 유틸리티 함수들을 전역레벨의 `function`으로 빼놓는걸 제안합니다.

제안하는 이유는 다음과 같은 이점을 기대하기 때문입니당
- `Object.assign` 할 필요없이 필요한곳에서 바로 사용할 수 있다
- 사용할때 `this`키워드 없이 사용할 수 있다

**Comment by mjkang0987** [comment]
음.. 이부분을 고민 많이했어요.
함수형으로 모듈 임포트를 할까, 프로토타입 상속을 할까..
이부분은 초반에 고민했던 내용이긴 합니당...
요거는 고민 조금 더 해볼게여!
